name: windows port

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-vs:
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
        configuration: [Debug]
        variant: [dev]
        visualstudio: ['2022']
        include:
        - visualstudio: '2022'
          runner: windows-2022
          vs_version: '[17, 18)'
        exclude:
        - variant: standard
          configuration: Debug
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Test background
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: "Aa123456"
        foreground: true
    - name: Install Visual Studio 2017
      if: matrix.visualstudio == '2017'
      run: |
        choco install visualstudio2017buildtools
        choco install visualstudio2017-workload-vctools
        choco install windows-sdk-8.1
    - uses: microsoft/setup-msbuild@v1
      with:
        vs-version: ${{ matrix.vs_version }}
    - uses: actions/setup-python@v4
      if: matrix.runner == 'windows-2019'
      with:
        python-version: '3.9' 
    - uses: actions/checkout@v3
    - name: Build mpy-cross.exe
      run: msbuild mpy-cross\mpy-cross.vcxproj -maxcpucount -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}
    - name: Build micropython.exe
      run: msbuild ports\windows\micropython.vcxproj -maxcpucount -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }} -property:PyVariant=${{ matrix.variant }} 
    - name: Get micropython.exe path
      id: get_path
      run: |
        $exePath="micropython=$((msbuild ports\windows\micropython.vcxproj -nologo -v:m -t:ShowTargetPath -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }} -property:PyVariant=${{ matrix.variant }}).Trim())"
        echo $exePath
        echo $exePath | Set-Content $env:GITHUB_OUTPUT
    - name: Run tests
      id: test
      env:
        MICROPY_MICROPYTHON: ${{ steps.get_path.outputs.micropython }}
      working-directory: tests
      run: python run-tests.py
    - name: Print failures
      if: failure() && steps.test.conclusion == 'failure'
      working-directory: tests
      run: python run-tests.py --print-failures
    - name: Run mpy tests
      id: test_mpy
      env:
        MICROPY_MICROPYTHON: ${{ steps.get_path.outputs.micropython }}
      working-directory: tests
      run: python run-tests.py --via-mpy -d basics float micropython
    - name: Print mpy failures
      if: failure() && steps.test_mpy.conclusion == 'failure'
      working-directory: tests
      run: python run-tests.py --print-failures
